export const jobList = [
  {
    id: "job_20251001_0001",
    slug: "frontend-developer",
    title: "Frontend Developer",
    type: "Full-time",
    status: "active",
    descriptions: "This is the job description. This is the job description. This is the job description.This is the job description.",
    company: "Rekamin 1",
    location: "Jakarta",
    salary_range: {
      min: 7000000,
      max: 8000000,
      currency: "IDR",
      display_text: "Rp7.000.000 - Rp8.000.000",
    },
    list_card: {
      badge: "Active",
      started_on_text: "started on 1 Oct 2025",
      cta: "Manage Job",
    },
  },
  {
    id: "job_20251001_0002",
    slug: "frontend-developer",
    title: "Frontend Developer",
    type: "Part-time",
    status: "inactive",
    descriptions: "This is the job description. This is the job description. This is the job description.This is the job description.",
    company: "Rekamin 2",
    location: "Jakarta Selatan",
    salary_range: {
      min: 7000000,
      max: 8000000,
      currency: "IDR",
      display_text: "Rp7.000.000 - Rp8.000.000",
    },
    list_card: {
      badge: "Active",
      started_on_text: "started on 1 Oct 2025",
      cta: "Manage Job",
    },
  },
  {
    id: "job_20251001_0003",
    slug: "frontend-developer",
    title: "Frontend Developer",
    type: "Freelance",
    status: "draft",
    descriptions: "This is the job description. This is the job description. This is the job description.This is the job description.",
    company: "Rekamin 3",
    location: "Jakarta Pusat",
    salary_range: {
      min: 7000000,
      max: 8000000,
      currency: "IDR",
      display_text: "Rp7.000.000 - Rp8.000.000",
    },
    list_card: {
      badge: "Active",
      started_on_text: "started on 1 Oct 2025",
      cta: "Manage Job",
    },
  },
];
