import type { CandidateResponse } from "@/features/jobs/type";

export const responseGetCandidate: CandidateResponse = {
  data: [
    {
      id: "cand_20251008_0001",
      attributes: [
        { key: "full_name", label: "Full Name", value: "Nadia Putri", order: 1 },
        { key: "email", label: "Email", value: "nadia.putri@example.com", order: 2 },
        { key: "phone", label: "Phone", value: "081212345678", order: 3 },
        { key: "domicile", label: "Domicile", value: "Jakarta", order: 4 },
        { key: "gender", label: "Gender", value: "Female", order: 5 },
        { key: "date_of_birth", label: "Date of Birth", value: "1990-01-01", order: 7 },
        { key: "photo_profile", label: "Photo Profile", value: "https://example.com/photo.jpg", order: 6 },
        { key: "linkedin_link", label: "LinkedIn", value: "https://linkedin.com/in/nadiaputri", order: 8 },
      ],
    },
    {
      id: "cand_20251008_0001",
      attributes: [
        { key: "full_name", label: "Full Name", value: "Nadia Putri", order: 1 },
        { key: "email", label: "Email", value: "nadia.putri@example.com", order: 2 },
        { key: "phone", label: "Phone", value: "081212345678", order: 3 },
        { key: "domicile", label: "Domicile", value: "Jakarta", order: 4 },
        { key: "gender", label: "Gender", value: "Female", order: 5 },
        { key: "date_of_birth", label: "Date of Birth", value: "1990-01-01", order: 7 },
        { key: "photo_profile", label: "Photo Profile", value: "https://example.com/photo.jpg", order: 6 },
        { key: "linkedin_link", label: "LinkedIn", value: "https://linkedin.com/in/nadiaputri", order: 8 },
      ],
    },
    {
      id: "cand_20251008_0001",
      attributes: [
        { key: "full_name", label: "Full Name", value: "Nadia Putri", order: 1 },
        { key: "email", label: "Email", value: "nadia.putri@example.com", order: 2 },
        { key: "phone", label: "Phone", value: "081212345678", order: 3 },
        { key: "domicile", label: "Domicile", value: "Jakarta", order: 4 },
        { key: "gender", label: "Gender", value: "Female", order: 5 },
        { key: "date_of_birth", label: "Date of Birth", value: "1990-01-01", order: 7 },
        { key: "photo_profile", label: "Photo Profile", value: "https://example.com/photo.jpg", order: 6 },
        { key: "linkedin_link", label: "LinkedIn", value: "https://linkedin.com/in/nadiaputri", order: 8 },
      ],
    },
    {
      id: "cand_20251008_0001",
      attributes: [
        { key: "full_name", label: "Full Name", value: "Nadia Putri", order: 1 },
        { key: "email", label: "Email", value: "nadia.putri@example.com", order: 2 },
        { key: "phone", label: "Phone", value: "081212345678", order: 3 },
        { key: "domicile", label: "Domicile", value: "Jakarta", order: 4 },
        { key: "gender", label: "Gender", value: "Female", order: 5 },
        { key: "date_of_birth", label: "Date of Birth", value: "1990-01-01", order: 7 },
        { key: "photo_profile", label: "Photo Profile", value: "https://example.com/photo.jpg", order: 6 },
        { key: "linkedin_link", label: "LinkedIn", value: "https://linkedin.com/in/nadiaputri", order: 8 },
      ],
    },
    {
      id: "cand_20251008_0001",
      attributes: [
        { key: "full_name", label: "Full Name", value: "Nadia Putri", order: 1 },
        { key: "email", label: "Email", value: "nadia.putri@example.com", order: 2 },
        { key: "phone", label: "Phone", value: "081212345678", order: 3 },
        { key: "domicile", label: "Domicile", value: "Jakarta", order: 4 },
        { key: "gender", label: "Gender", value: "Female", order: 5 },
        { key: "date_of_birth", label: "Date of Birth", value: "1990-01-01", order: 7 },
        { key: "photo_profile", label: "Photo Profile", value: "https://example.com/photo.jpg", order: 6 },
        { key: "linkedin_link", label: "LinkedIn", value: "https://linkedin.com/in/nadiaputri", order: 8 },
      ],
    },
    {
      id: "cand_20251008_0001",
      attributes: [
        { key: "full_name", label: "Full Name", value: "Nadia Putri", order: 1 },
        { key: "email", label: "Email", value: "nadia.putri@example.com", order: 2 },
        { key: "phone", label: "Phone", value: "081212345678", order: 3 },
        { key: "domicile", label: "Domicile", value: "Jakarta", order: 4 },
        { key: "gender", label: "Gender", value: "Female", order: 5 },
        { key: "date_of_birth", label: "Date of Birth", value: "1990-01-01", order: 7 },
        { key: "photo_profile", label: "Photo Profile", value: "https://example.com/photo.jpg", order: 6 },
        { key: "linkedin_link", label: "LinkedIn", value: "https://linkedin.com/in/nadiaputri", order: 8 },
      ],
    },
    {
      id: "cand_20251008_0001",
      attributes: [
        { key: "full_name", label: "Full Name", value: "Nadia Putri", order: 1 },
        { key: "email", label: "Email", value: "nadia.putri@example.com", order: 2 },
        { key: "phone", label: "Phone", value: "081212345678", order: 3 },
        { key: "domicile", label: "Domicile", value: "Jakarta", order: 4 },
        { key: "gender", label: "Gender", value: "Female", order: 5 },
        { key: "date_of_birth", label: "Date of Birth", value: "1990-01-01", order: 7 },
        { key: "photo_profile", label: "Photo Profile", value: "https://example.com/photo.jpg", order: 6 },
        { key: "linkedin_link", label: "LinkedIn", value: "https://linkedin.com/in/nadiaputri", order: 8 },
      ],
    },
    {
      id: "cand_20251008_0001",
      attributes: [
        { key: "full_name", label: "Full Name", value: "Nadia Putri", order: 1 },
        { key: "email", label: "Email", value: "nadia.putri@example.com", order: 2 },
        { key: "phone", label: "Phone", value: "081212345678", order: 3 },
        { key: "domicile", label: "Domicile", value: "Jakarta", order: 4 },
        { key: "gender", label: "Gender", value: "Female", order: 5 },
        { key: "date_of_birth", label: "Date of Birth", value: "1990-01-01", order: 7 },
        { key: "photo_profile", label: "Photo Profile", value: "https://example.com/photo.jpg", order: 6 },
        { key: "linkedin_link", label: "LinkedIn", value: "https://linkedin.com/in/nadiaputri", order: 8 },
      ],
    },
    {
      id: "cand_20251008_0001",
      attributes: [
        { key: "full_name", label: "Full Name", value: "Nadia Putri", order: 1 },
        { key: "email", label: "Email", value: "nadia.putri@example.com", order: 2 },
        { key: "phone", label: "Phone", value: "081212345678", order: 3 },
        { key: "domicile", label: "Domicile", value: "Jakarta", order: 4 },
        { key: "gender", label: "Gender", value: "Female", order: 5 },
        { key: "date_of_birth", label: "Date of Birth", value: "1990-01-01", order: 7 },
        { key: "photo_profile", label: "Photo Profile", value: "https://example.com/photo.jpg", order: 6 },
        { key: "linkedin_link", label: "LinkedIn", value: "https://linkedin.com/in/nadiaputri", order: 8 },
      ],
    },
    {
      id: "cand_20251008_0001",
      attributes: [
        { key: "full_name", label: "Full Name", value: "Nadia Putri", order: 1 },
        { key: "email", label: "Email", value: "nadia.putri@example.com", order: 2 },
        { key: "phone", label: "Phone", value: "081212345678", order: 3 },
        { key: "domicile", label: "Domicile", value: "Jakarta", order: 4 },
        { key: "gender", label: "Gender", value: "Female", order: 5 },
        { key: "date_of_birth", label: "Date of Birth", value: "1990-01-01", order: 7 },
        { key: "photo_profile", label: "Photo Profile", value: "https://example.com/photo.jpg", order: 6 },
        { key: "linkedin_link", label: "LinkedIn", value: "https://linkedin.com/in/nadiaputri", order: 8 },
      ],
    },
  ],
};
